# Generated by Django 4.1.1 on 2023-01-17 20:06

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("founder", models.EmailField(default="Email", max_length=255)),
                ("project_name", models.CharField(max_length=30)),
                ("slug", models.CharField(max_length=200, unique=True)),
                ("investment", models.IntegerField()),
                ("description", models.TextField()),
                ("website", models.URLField()),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("Pre Seed", "Pre Seed"),
                            ("seed", "Seed"),
                            ("Series A B", "Series A B"),
                            ("Series C", "Series C"),
                        ],
                        default="Pre Seed",
                        max_length=15,
                    ),
                ),
                (
                    "industry",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("ecommerse_and_retail", "Ecommerse andretail tech"),
                            ("delivery_services", "Delivery Services"),
                            ("healthcare_tech", "Healthcare Tech"),
                            ("artificial_intelligence", "Aritificial Intelligence"),
                            ("vr", "Virtual Reality"),
                            ("ed_tech", "Educational Tech"),
                            ("fin_tech", "Financial Tech"),
                            ("big_data", "Big Data"),
                            (
                                "supply_chain_management_logistic",
                                "Supply Chain Management Logistic",
                            ),
                            ("media_entertainment", "Media and Entertainment"),
                            ("real_estate", "Real Estate"),
                            ("b2b_software", "B2B software"),
                            ("shared_mobility", "Shared Mobility"),
                            ("transportation", "Transportation"),
                            ("hr_tech", "HR Tech"),
                            ("comp_hardware", "Computer Hardware"),
                            (
                                "services",
                                "Professional, scientific and technical services",
                            ),
                            ("networking", "Networking"),
                            ("ads_marketing", "Advertising and Marketing"),
                            ("streaming_services", "Streaming Services"),
                            ("manufacturing", "Manufacturing"),
                            ("eco_waste_management", "Ecology and Waste Management"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(max_length=2, null=True),
                ),
                ("end_date", models.DateField(default=django.utils.timezone.now)),
                ("project_image", models.ImageField(null=True, upload_to="projects/")),
                ("presentation", models.URLField(null=True)),
                ("video", models.URLField(null=True)),
                ("papers", models.URLField(null=True)),
            ],
        ),
    ]
