# Generated by Django 4.1.1 on 2023-01-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project", name="slug", field=models.SlugField(unique=True),
        ),
    ]
