# Generated by Django 4.1.1 on 2023-01-23 10:19

from django.db import migrations, models
import django.utils.timezone
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_image",
            field=models.ImageField(null=True, upload_to=projects.models.upload_path),
        ),
    ]
