# Generated by Django 4.1.1 on 2023-01-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_meeting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="choosen_time",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="founder",
            field=models.EmailField(default="Email", max_length=255),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="invitee",
            field=models.EmailField(default="Email", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="option_1_time",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="option_2_time",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="option_3_time",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.project"
            ),
        ),
    ]
