# Generated by Django 4.1.1 on 2023-01-23 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0006_delete_meeting"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_1_time", models.CharField(blank=True, max_length=100)),
                ("option_2_time", models.CharField(blank=True, max_length=100)),
                ("option_3_time", models.CharField(blank=True, max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("is_accepted", models.BooleanField(default=False)),
                ("founder", models.EmailField(default="Email", max_length=255)),
                (
                    "invitee",
                    models.EmailField(default="Email", max_length=254, unique=True),
                ),
                ("choosen_time", models.DateTimeField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
