# Generated by Django 4.1.1 on 2023-01-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="choosen_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="option_1_time",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="option_2_time",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="option_3_time",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
