# Generated by Django 4.1.1 on 2023-01-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0003_alter_meeting_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meeting", old_name="choosen_time", new_name="chosen_time",
        ),
    ]
