# Generated by Django 4.1.1 on 2023-01-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0005_meeting_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="chosen_time",
            field=models.DateTimeField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="description",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="invitee",
            field=models.EmailField(default="Email", max_length=254),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="link",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="option_1_time",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="option_2_time",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="option_3_time",
            field=models.CharField(default="", max_length=100, null=True),
        ),
    ]
