# Generated by Django 4.1.1 on 2023-01-04 15:49

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("investment", models.PositiveIntegerField()),
                ("description", models.TextField()),
                ("website", models.URLField()),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("Pre Seed", "Pre Seed"),
                            ("seed", "Seed"),
                            ("Series A B", "Series A B"),
                            ("Series C", "Series C"),
                        ],
                        default="Pre Seed",
                        max_length=15,
                    ),
                ),
                (
                    "industry",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("Ecommerse and Retail Tech", "Ecommerse Retail"),
                            ("Delivery Services", "Delivery Services"),
                            ("Healthcare Tech", "Healthcare Tech"),
                            ("Artificial Intelligence", "Ai"),
                            ("Virtual Reality", "Vr"),
                            ("Educational Tech", "Ed Tech"),
                            ("Financial Tech", "Fin Tech"),
                            ("Big Data", "Big Data"),
                            (
                                "Supply chain Management Logistic",
                                "Supply Chain Management Logistic",
                            ),
                            ("Media and Entertainment", "Media Entertainment"),
                            ("Real Estate", "Real Estate"),
                            ("B2B software", "B2B"),
                            ("Shared Mobility", "Shared Mobility"),
                            ("Transportation", "Transportation"),
                            ("HR Tech", "Hr Tech"),
                            ("Computer Hardware", "Comp Hardware"),
                            (
                                "Professional, Scientific and Technical Services",
                                "Services",
                            ),
                            ("Networking", "Networking"),
                            ("Advertising and Marketing", "Ads Marketing"),
                            ("Streaming Services", "Streaming Services"),
                            ("Manufacturing", "Manufacturing"),
                            ("Ecology and Waste Management", "Eco Waste Management"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(max_length=2, null=True),
                ),
                ("end_date", models.DateField(default=django.utils.timezone.now)),
                ("project_image", models.ImageField(null=True, upload_to="projects/")),
                ("presentation", models.URLField(null=True)),
                ("video", models.URLField(null=True)),
                ("papers", models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=200, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_founder", models.BooleanField(default=False)),
                ("is_investor", models.BooleanField(default=False)),
                ("has_subscription", models.BooleanField(default=False)),
                (
                    "saved_projects",
                    models.ManyToManyField(
                        blank=True, related_name="saved_by", to="accounts.projects"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
