# Generated by Django 4.1.1 on 2023-01-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="useraccount", name="is_investor",),
    ]
