# Generated by Django 4.1.1 on 2023-01-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_useraccount_is_investor"),
    ]

    operations = [
        migrations.RemoveField(model_name="useraccount", name="saved_projects",),
        migrations.DeleteModel(name="Projects",),
    ]
